---

- name: install the system
  hosts: "127.0.0.1"
  vars:
          ansible_python_interpreter: /usr/bin/python3
  become: yes
  connection: local

  tasks:
        - name: do stuff
          include_role:
                name: install_software
