---

- name: set up repositories
  yum_repository: "{{ item }}"
  with_items:
  - name: vivaldi
    description: vivaldi Browser repository
    baseurl: http://repo.vivaldi.com/stable/rpm/x86_64
    gpgkey: http://repo.vivaldi.com/stable/linux_signing_key.pub 

  - name: vscode
    description: MS Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    
  - name: spotify
    description: Spotify Client
    baseurl: https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh

  - name: steam
    description: steam client
    baseurl: https://negativo17.org/repos/steam/fedora-$releasever/$basearch/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh


- name: install software packages
  yum: 
    name: 
    - vivaldi-stable
    - git
    - code
    - spotify-client
    - keepass
    - zsh
    - seafile-client
    - glances
    - steam

- name: install i3
  yum:
    name:
    - i3 
    - i3status 
    - dmenu 
    - i3lock 
    - xbacklight 
    - feh 
    - conky
