---

- name: set up repositories
  yum_repository: "{{ item }}"
  with_items:
    - name: vivaldi
      description: vivaldi Browser repository
      baseurl: http://repo.vivaldi.com/stable/rpm/x86_64
      gpgkey: http://repo.vivaldi.com/stable/linux_signing_key.pub 

    - name: vscode
      description: MS Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc


- name: install software packages
  yum: 
        name: 
          - vivaldi-stable
          - git
          - code
